# Generated by Django 3.2.23 on 2023-11-06 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proyecttask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
